(function(){
const themes=[
{id:'night',name:'Night Study',price:120,image:'assets/1/bg-cat-night.svg'},
{id:'sky',name:'Sky Day',price:150,image:'assets/1/bg-sky.svg'},
{id:'pink',name:'Pink Mood',price:180,image:'assets/1/bg-pink.svg'},
{id:'ocean',name:'Ocean Calm',price:220,image:'assets/1/bg-ocean.svg'},
{id:'lavender',name:'Lavender Dream',price:260,image:'assets/1/bg-lavender.svg'}
];
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('en-US');
function applyTheme(id,save=true){const t=themes.find(x=>x.id===id);if(!t){document.body.style.removeProperty('background-image');if(save)localStorage.removeItem('katlearn-theme');return}document.body.style.backgroundImage=`linear-gradient(180deg,rgba(255,255,255,.18),rgba(255,255,255,.18)),url('${t.image}')`;document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';document.body.style.backgroundPosition='center';if(save)localStorage.setItem('katlearn-theme',id)}
function paint(p){if(!p)return;localStorage.setItem('katlearn-vocab',JSON.stringify(Array.isArray(p.vocab)?p.vocab:[]));if(p.themeId)localStorage.setItem('katlearn-theme',p.themeId);else localStorage.removeItem('katlearn-theme');['#coinCount','#shopCoins','#panelCoins'].forEach(s=>{const e=$(s);if(e)e.textContent=fmt(p.coins)});const en=$('#panelEnergy');if(en)en.textContent=fmt(p.energy);const w=$('#panelWords');if(w)w.textContent=fmt(Array.isArray(p.vocab)?p.vocab.length:p.totalWords);const k=$('#knownCount');if(k)k.textContent=fmt(p.knownWords);const tot=$('#totalWords');if(tot)tot.textContent=fmt(Array.isArray(p.vocab)?p.vocab.length:p.totalWords);applyTheme(p.themeId||'default',false);const cards=document.querySelectorAll('#progress .stat-grid>div'),a=Number(p.questionsAnswered||0),c=Number(p.correctAnswers||0),acc=a?Math.round(c/a*100):0,vals=[Number(p.knownWords||0),acc+'%',Number(p.streak||0),fmt(p.coins)];cards.forEach((x,i)=>{const h=x.querySelector('h2');if(h)h.textContent=vals[i]})}
async function hydrate(){if(!window.studyStore?.user)return;try{const p=await window.studyStore.loadProfile();if(p)paint(p);else localStorage.setItem('katlearn-vocab','[]')}catch(e){console.warn('[KatLearn cloud]',e)}}
function patch(){if(!window.studyStore||window.studyStore.__cloudPatch)return;const old=window.studyStore.saveProfile.bind(window.studyStore);window.studyStore.saveProfile=async data=>{const vocab=JSON.parse(localStorage.getItem('katlearn-vocab')||'[]');return old({...data,vocab,totalWords:vocab.length,knownWords:Number($('#knownCount')?.textContent||data?.knownWords||0),themeId:localStorage.getItem('katlearn-theme')||'default'})};window.studyStore.__cloudPatch=true}
async function shop(){const g=$('.shop-grid');if(!g)return;let bought=new Set();if(window.studyStore?.user){try{(await window.studyStore.purchasedItems()).forEach(x=>bought.add(x.id))}catch(e){}}const current=localStorage.getItem('katlearn-theme')||'default';g.innerHTML=themes.map(t=>`<article class="shop-theme-card"><div class="shop-theme-preview" style="background-image:url('${t.image}')"></div><h3>${t.name}</h3><p>Hình nền KatLearn</p><b>🪙 ${fmt(t.price)}</b><button class="shop-buy-theme" data-price="${t.price}" data-theme-id="${t.id}" data-item-id="theme-${t.id}">${bought.has('theme-'+t.id)?'✓ Đã mua':'Mua'}</button><button class="shop-apply-theme" data-theme-id="${t.id}" ${bought.has('theme-'+t.id)||current===t.id?'':'disabled'}>${current===t.id?'✓ Đang áp dụng':'Áp dụng'}</button></article>`).join('')}
document.addEventListener('click',e=>{const a=e.target.closest?.('.shop-apply-theme');if(a){e.preventDefault();e.stopPropagation();const id=a.dataset.themeId;applyTheme(id);if(window.studyStore?.user)window.studyStore.saveProfile({themeId:id,__coinsAuthoritative:false});setTimeout(shop,100);return}const b=e.target.closest?.('.shop-buy-theme');if(b)setTimeout(shop,1000)},true);
window.addEventListener('8b1-auth-change',()=>setTimeout(async()=>{patch();await hydrate();await shop()},0));
document.addEventListener('DOMContentLoaded',async()=>{patch();await hydrate();await shop()},{once:true});
setTimeout(()=>applyTheme(localStorage.getItem('katlearn-theme')||'default',false),0);
})();
