let vocab=[];
try{const savedVocab=JSON.parse(localStorage.getItem('katlearn-vocab')||'[]');if(Array.isArray(savedVocab))vocab=savedVocab}catch(e){}
let coins=0,energy=0,cardIndex=0,known=0,question=1,sessionCoins=0,mode='engvi',answered=false;
const $=s=>document.querySelector(s),$=s=>document.querySelectorAll(s);
const aiEndpoint=name=>(location.hostname==='localhost'||location.hostname==='127.0.0.1')?'/api/'+name:'/.netlify/functions/'+name;
async function aiHeaders(){const h={'Content-Type':'application/json'};try{const t=await window.studyStore?.getIdToken?.();if(t)h.Authorization='Bearer '+t}catch(_){}return h}
function format(n){return n.toLocaleString('en-US')}
function updateCoins(){['#coinCount','#shopCoins','#panelCoins'].forEach(s=>$(s).textContent=format(coins));$('#panelEnergy').textContent=format(energy);$('#panelWords').textContent=vocab.length}
async function syncProfile(extra={}){if(window.studyStore?.connected()&&window.studyStore.user)try{await window.studyStore.saveProfile({coins,energy,streak:0,knownWords:known,totalWords:vocab.length,...extra})}catch(e){console.warn('Firebase sync:',e)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active-page'));$('#'+id).classList.add('active-page');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('.sidebar').classList.remove('open');if(id==='ranking')renderLeaderboard();if(id==='packs')renderPublicPacks();if(id==='words')renderVocabularyViews();window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));$('.start-lesson').onclick=()=>showPage('learn');$('.menu-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
function renderWordList(){const list=$('#wordList');list.innerHTML=vocab.length?vocab.map((v,i)=>`<button class="word-item ${i===cardIndex?'selected':''}" data-index="${i}">${esc(v.word)}<small>${esc(v.pron||'Chưa có phiên âm')}</small>${i<known?'<i>✓</i>':''}</button>`).join(''):'<p class="empty-state">Chưa có từ nào.</p>';$$('.word-item').forEach(b=>b.onclick=()=>{cardIndex=+b.dataset.index;renderCard()});['#wordListCount','#totalWords','#cardTotal'].forEach(s=>$(s).textContent=vocab.length)}
function renderVocabularyViews(filter=''){const q=filter.trim().toLowerCase(),visible=vocab.filter(v=>!q||v.word.toLowerCase().includes(q)||v.mean.toLowerCase().includes(q)),total=vocab.length,done=Math.min(known,total),progress=total?Math.round(done/total*100):0;$('#wordTotalStat').textContent=total;$('#wordKnownStat').textContent=done;$('#wordUnknownStat').textContent=Math.max(0,total-done);$('#wordProgressStat').textContent=progress+'%';$('#personalWordCount').textContent=total;$('#personalKnownCount').textContent=done;$('#personalPackCount').textContent=total?1:0;$('#wordTable').innerHTML=visible.length?visible.map((v,i)=>`<div class="word-table-row"><span><b>${esc(v.word)}</b><small>${i+1}/${total}</small></span><span>${esc(v.mean)}</span><span>${esc(v.pron||'—')}</span><span><i class="word-status ${i<done?'':'new'}">${i<done?'Đã thuộc':'Mới'}</i></span></div>`).join(''):'<div class="empty-state">Chưa có từ phù hợp.</div>'}
function renderCard(){if(!vocab.length){$('#cardWord').textContent='Chưa có từ vựng';$('#cardPronounce').textContent='Hãy thêm từ đầu tiên của bạn';$('#cardMeaning').innerHTML='Kat đang<br>chờ bạn!';$('.card-front .card-visual').textContent='🐱';$('#cardStep').textContent='00';renderWordList();renderVocabularyViews();return}const v=vocab[cardIndex%vocab.length];$('#cardWord').textContent=v.word;$('#cardPronounce').textContent=v.pron||'—';$('#cardMeaning').innerHTML=esc(v.mean).replace(/ /g,'<br>');$('.card-front .card-visual').textContent=v.emoji;$('#cardStep').textContent=String(cardIndex+1).padStart(2,'0');$('.flashcard').classList.remove('flipped');renderWordList();renderVocabularyViews()}
$('#flashcard').onclick=()=>{if(vocab.length)$('#flashcard').classList.toggle('flipped')};$('#prevCard').onclick=()=>{if(!vocab.length)return;cardIndex=(cardIndex+vocab.length-1)%vocab.length;renderCard()};$('#nextCard').onclick=()=>{if(!vocab.length)return;cardIndex=(cardIndex+1)%vocab.length;renderCard()};$('#knowBtn').onclick=()=>{if(!vocab.length)return toast('Hãy thêm từ vựng trước nhé!');known=Math.min(vocab.length,known+1);$('#knownCount').textContent=known;syncProfile();toast('Đã ghi nhận! Bạn đang tiến bộ rất tốt ✨');cardIndex=(cardIndex+1)%vocab.length;renderCard()};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
async function loadAiContext(v){const fallback=`I <b>${esc(v.word)}</b> is a useful word to practise every day.`;$('#questionWord').innerHTML=fallback;try{const res=await fetch(aiEndpoint('context-example'),{method:'POST',headers:await aiHeaders(),body:JSON.stringify({word:v.word,meaning:v.mean})});const data=await res.json();if(res.ok&&data.text)$('#questionWord').textContent=data.text;else $('#questionHint').textContent='AI chưa được cấu hình — dùng câu ví dụ mặc định:'}catch(e){$('#questionHint').textContent='AI chỉ hoạt động khi chạy server — dùng câu ví dụ mặc định:'}}
function renderQuiz(){answered=false;if(!vocab.length){$('#questionHint').textContent='Bạn cần thêm từ vựng trước khi luyện tập.';$('#questionWord').textContent='Chưa có bộ từ';$('#questionPronounce').textContent='';$('#answers').innerHTML='<button class="answer" id="goAddWords"><b>＋</b> Thêm từ vựng ngay</button>';$('#goAddWords').onclick=()=>showPage('learn');$('#feedback').textContent='';return}const v=vocab[(question-1)%vocab.length];let correct,answers,hint,word,pron='';if(mode==='engvi'){hint='Chọn nghĩa tiếng Việt của từ:';word=v.word;pron=v.pron;correct=v.mean;answers=shuffle(vocab.map(x=>x.mean))}else if(mode==='vieng'){hint='Chọn từ tiếng Anh phù hợp với nghĩa:';word=v.mean;correct=v.word;answers=shuffle(vocab.map(x=>x.word))}else{hint='Từ in đậm trong ngữ cảnh có nghĩa là gì?';word=`I <b>${v.word}</b> is a useful word to practise every day.`;correct=v.mean;answers=shuffle(vocab.map(x=>x.mean));}
 $('#questionHint').textContent=hint;$('#questionWord').innerHTML=mode==='context'?word:esc(word);$('#questionPronounce').textContent=pron;$('#questionNumber').textContent=question;$('#quizProgress').style.width=question*10+'%';const labels=['A','B','C','D','E'];$('#answers').innerHTML=answers.slice(0,4).map((a,i)=>`<button class="answer" data-right="${a===correct}"><b>${labels[i]}</b>${esc(a)}</button>`).join('');if(!answers.slice(0,4).includes(correct)){$('#answers').lastElementChild.innerHTML=`<b>D</b>${esc(correct)}`;$('#answers').lastElementChild.dataset.right='true'}$('#feedback').textContent='';$$('.answer').forEach(btn=>btn.onclick=()=>answer(btn,correct));if(mode==='context')loadAiContext(v);}
function answer(btn,correct){if(answered)return;answered=true;const good=btn.dataset.right==='true',v=vocab[(question-1)%vocab.length];$$('.answer').forEach(b=>{if(b.dataset.right==='true')b.classList.add('correct')});if(good){sessionCoins+=10;coins+=10;energy+=10;updateCoins();syncProfile();$('#sessionCoins').textContent=sessionCoins;$('#feedback').textContent='Chính xác! +10 xu 🪙'}else{btn.classList.add('wrong');$('#feedback').textContent=`Đáp án đúng là: ${correct}`;$('#feedback').style.color='#e36b63'}window.studyStore?.recordAnswer({word:v.word,meaning:v.mean,mode,correct:good,reviewDueAt:Date.now()+30*24*60*60*1000});setTimeout(()=>{if(question>=10){$('#reward').textContent=`+${sessionCoins} 🪙`;$('#resultModal').classList.add('show');question=1;sessionCoins=0;$('#sessionCoins').textContent='0'}else{question++;renderQuiz()}},900)}
$$('.mode-card').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.mode-card').forEach(x=>x.classList.toggle('active-mode',x===b));question=1;renderQuiz()});$('.close-modal').onclick=()=>{$('#resultModal').classList.remove('show');renderQuiz()};
$$('.shop-grid button').forEach((b,i)=>b.onclick=()=>{const price=+b.dataset.price;if(coins>=price){coins-=price;updateCoins();syncProfile();window.studyStore?.purchase({id:`item-${i+1}`,name:b.closest('article').querySelector('h3').textContent,price});b.textContent='✓ Đã mua';b.disabled=true;toast('Đã thêm vật phẩm vào bộ sưu tập!')}else toast('Bạn chưa đủ xu cho vật phẩm này.')});
$('#addWordBtn').onclick=()=>$('#wordModal').classList.add('show');$('#closeWordModal').onclick=()=>$('#wordModal').classList.remove('show');$('#wordModal').onclick=e=>{if(e.target===$('#wordModal'))$('#wordModal').classList.remove('show')};$('#wordForm').onsubmit=e=>{e.preventDefault();const item={word:$('#newWord').value.trim(),mean:$('#newMeaning').value.trim(),pron:$('#newPronounce').value.trim(),emoji:$('#newEmoji').value};if(vocab.some(v=>v.word.toLowerCase()===item.word.toLowerCase()))return toast('Từ vựng này đã có trong danh sách.');vocab.push(item);localStorage.setItem('katlearn-vocab',JSON.stringify(vocab));cardIndex=vocab.length-1;$('#wordForm').reset();$('#wordModal').classList.remove('show');renderCard();renderQuiz();syncProfile();toast(`Đã thêm “${item.word}” vào bộ từ của bạn!`)};
$('#addWordFromList').onclick=()=>$('#wordModal').classList.add('show');$('#createPersonalPack').onclick=()=>{$('#wordModal').classList.add('show');toast('Thêm từ đầu tiên để bắt đầu bộ từ cá nhân của bạn.')} ;$('#openFlashcards').onclick=()=>showPage('learn');$('#wordSearch').oninput=e=>renderVocabularyViews(e.target.value);
function esc(text){return String(text||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function renderLeaderboard(){const target=$('#rankingContent'),mini=$('#miniRanking');if(!window.studyStore?.user){const note='Đăng nhập để xem bảng xếp hạng thực tế. 🐱';target.textContent=note;mini.textContent='Đăng nhập và học để xuất hiện trên bảng xếp hạng. 🐾';return}try{const users=await window.studyStore.leaderboard();if(!users.length){target.textContent='Chưa có thành tích nào. Hãy là người đầu tiên học cùng Kat! 🐾';mini.textContent='Chưa có thành tích nào.';return}const rows=users.map((u,i)=>`<div class="rank-list-row ${u.id===window.studyStore.userId?'mine':''}"><b>${String(i+1).padStart(2,'0')}</b><span class="rank-avatar">${esc((u.displayName||'K')[0]).toUpperCase()}</span><strong>${esc(u.displayName||'KatLearn Student')}</strong><small>⚡ ${Number(u.energy||0).toLocaleString('en-US')} năng lượng</small><i>🪙 ${Number(u.coins||0).toLocaleString('en-US')}</i></div>`).join('');target.innerHTML=rows;mini.innerHTML=users.slice(0,3).map((u,i)=>`<div class="rank-row"><b>${String(i+1).padStart(2,'0')}</b><span class="rank-avatar">${esc((u.displayName||'K')[0]).toUpperCase()}</span><strong>${esc(u.displayName||'KatLearn Student')}</strong><span>⚡ ${Number(u.energy||0)}</span></div>`).join('')}catch(e){target.textContent='Chưa thể tải bảng xếp hạng.';mini.textContent='Chưa thể tải bảng xếp hạng.'}}
function renderPackLibrary(packs=[]){const library=$('#packLibrary');if(!window.studyStore?.user){library.innerHTML='<div class="empty-state">Đăng nhập để xem các pack từ vựng công khai. 🐾</div>';return}const current=vocab.length?[{id:'current',name:'Bộ từ đang học',words:vocab,current:true},...packs]:packs;library.innerHTML=current.length?current.map(pack=>`<article class="pack-tile"><div class="tile-icon">${pack.current?'🐱':'📚'}</div><h3>${esc(pack.name)}</h3><p>${pack.words.length} từ vựng · ${pack.current?'Bộ từ cá nhân':'Cộng đồng KatLearn'}</p><button data-pack="${pack.id}">${pack.current?'Tiếp tục học':'Mở pack'} →</button></article>`).join(''):'<div class="empty-state">Chưa có pack. Hãy tạo bộ từ đầu tiên của bạn. 🐱</div>';$$('[data-pack]').forEach(btn=>btn.onclick=()=>{const pack=current.find(p=>p.id===btn.dataset.pack);if(!pack)return;if(!pack.current){vocab=pack.words;known=0;cardIndex=0;localStorage.setItem('katlearn-vocab',JSON.stringify(vocab));renderCard();renderQuiz()}showPage('learn');toast(`Đã mở “${pack.name}”.`)})}
async function renderPublicPacks(){const target=$('#publishedPacks'),adminList=$('#publicPackList');if(!window.studyStore?.user){target.textContent='Đăng nhập để xem các pack từ vựng công khai.';renderPackLibrary();return}try{const packs=await window.studyStore.publicPacks();const body=packs.length?packs.map(pack=>`<div class="published-pack"><span>📚</span><div><b>${esc(pack.name)}</b><small>${pack.words.length} từ vựng</small></div><button data-public-pack="${pack.id}">Học pack</button></div>`).join(''):'<div class="empty-state">Chưa có pack công khai.</div>';target.innerHTML=`<b>Pack từ vựng công khai</b>${body}`;if(adminList)adminList.innerHTML=body;renderPackLibrary(packs);$$('[data-public-pack]').forEach(btn=>btn.onclick=()=>{const pack=packs.find(p=>p.id===btn.dataset.publicPack);vocab=pack.words;known=0;cardIndex=0;localStorage.setItem('katlearn-vocab',JSON.stringify(vocab));renderCard();renderQuiz();showPage('learn');toast(`Đã tải pack “${pack.name}”.`)});}catch(e){target.textContent='Chưa thể tải pack công khai.';renderPackLibrary();if(adminList)adminList.textContent='Chưa thể tải danh sách pack.'}}
function renderAdmin(user){const canAdmin=!!user&&window.studyStore.isAdmin();$('.admin-nav').hidden=!canAdmin;if(!canAdmin&&$('#admin').classList.contains('active-page'))showPage('home')}
function packRow(data={}){const row=document.createElement('div');row.className='pack-word-row';row.innerHTML=`<input class="pack-english" value="${esc(data.word)}" maxlength="60" placeholder="Tiếng Anh" required><input class="pack-vietnamese" value="${esc(data.mean)}" maxlength="100" placeholder="AI tự điền nghĩa" required><input class="pack-pronunciation" value="${esc(data.pron)}" maxlength="70" placeholder="AI tự điền phiên âm"><button class="remove-row-btn" type="button" title="Xóa từ">×</button>`;row.querySelector('.remove-row-btn').onclick=()=>{if($$('.pack-word-row').length===1)return toast('Pack cần ít nhất một từ vựng.');row.remove()};const english=row.querySelector('.pack-english');english.addEventListener('input',()=>{clearTimeout(row.aiTimer);row.aiTimer=setTimeout(()=>fillPackWord(row),700)});return row}
async function fillPackWord(row){const word=row.querySelector('.pack-english').value.trim(),mean=row.querySelector('.pack-vietnamese'),pron=row.querySelector('.pack-pronunciation');if(!word)return;row.dataset.word=word;[mean,pron].forEach(x=>{x.classList.add('ai-filling');x.placeholder='Kat AI đang xử lý…'});try{const res=await fetch(aiEndpoint('vocab-assist'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({word})}),data=await res.json();if(!res.ok)throw new Error(data.error||'AI chưa sẵn sàng');if(row.dataset.word!==word)return;mean.value=data.meaning||mean.value;pron.value=data.pronunciation||pron.value;toast(`Kat AI đã điền nghĩa và phiên âm cho “${word}”.`)}catch(error){mean.placeholder='Tự nhập nghĩa tiếng Việt';pron.placeholder='Tự nhập phiên âm';toast('Kat AI chưa được kích hoạt — bạn vẫn có thể tự điền hai ô.')}finally{[mean,pron].forEach(x=>x.classList.remove('ai-filling'))}}
function resetPackRows(){const rows=$('#packWordRows');rows.innerHTML='';rows.append(packRow(),packRow(),packRow())}
$('#openPackModal').onclick=()=>{resetPackRows();$('#publicPackName').value='';$('#packModal').classList.add('show')};$('#closePackModal').onclick=()=>$('#packModal').classList.remove('show');$('#packModal').onclick=e=>{if(e.target===$('#packModal'))$('#packModal').classList.remove('show')};$('#addPackRow').onclick=()=>$('#packWordRows').append(packRow());$('#publicPackForm').onsubmit=async e=>{e.preventDefault();if(!window.studyStore.isAdmin())return toast('Tài khoản này chưa có quyền admin.');const words=[...$$('.pack-word-row')].map(row=>({word:row.querySelector('.pack-english').value.trim(),mean:row.querySelector('.pack-vietnamese').value.trim(),pron:row.querySelector('.pack-pronunciation').value.trim(),emoji:'📚'})).filter(item=>item.word&&item.mean);if(!words.length)return toast('Pack cần ít nhất một từ đủ Anh–Việt.');try{await window.studyStore.createPublicPack({name:$('#publicPackName').value.trim(),words});$('#packModal').classList.remove('show');await renderPublicPacks();toast(`Đã xuất bản pack gồm ${words.length} từ vựng!`)}catch(err){toast('Không thể xuất bản: '+err.message)}};$('#copySecretCommand').onclick=async()=>{try{await navigator.clipboard.writeText('firebase functions:secrets:set OPENAI_API_KEY');toast('Đã sao chép lệnh Firebase Secret.')}catch(e){toast('Hãy sao chép lệnh hiển thị bên trên.')}};
const savedFirebase=localStorage.getItem('8b1-firebase-config'),defaultFirebase=window.KATLEARN_FIREBASE_CONFIG;const firebaseConfig=savedFirebase?JSON.parse(savedFirebase):defaultFirebase;$('#firebaseConfig').value=JSON.stringify(firebaseConfig,null,2);window.studyStore.connect(firebaseConfig).then(()=>syncProfile()).catch(e=>console.warn('Firebase chưa kết nối:',e));$('#settingsBtn').onclick=()=>$('#settingsModal').classList.add('show');$('#closeSettingsModal').onclick=()=>$('#settingsModal').classList.remove('show');$('#settingsModal').onclick=e=>{if(e.target===$('#settingsModal'))$('#settingsModal').classList.remove('show')};$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{const config=JSON.parse($('#firebaseConfig').value);await window.studyStore.connect(config);localStorage.setItem('8b1-firebase-config',JSON.stringify(config));await syncProfile();$('#settingsModal').classList.remove('show');toast('Đã kết nối Firebase và bắt đầu đồng bộ dữ liệu!')}catch(err){toast('Firebase config không hợp lệ: '+err.message)}};
function renderAuth(user){const login=$('#loginBtn'),trigger=$('#accountTrigger'),panel=$('#accountPanel');login.hidden=!!user;trigger.hidden=!user;if(!user){panel.hidden=true;login.onclick=()=>$('#loginModal').classList.add('show');return}const name=user.displayName||user.email?.split('@')[0]||'KatLearn Student',initial=name.trim()[0].toUpperCase();['#accountAvatar','#panelAvatar'].forEach(s=>{const avatar=$(s);avatar.textContent=initial;if(user.photoURL){avatar.style.backgroundImage=`url("${user.photoURL}")`;avatar.style.backgroundSize='cover';avatar.style.color='transparent'}else{avatar.style.backgroundImage='';avatar.style.color='#fff'}});$('#accountName').textContent=name;$('#panelName').textContent=name;$('#panelEmail').textContent=user.email||'';updateCoins();trigger.onclick=()=>panel.hidden=!panel.hidden;panel.hidden=false}
async function refreshAuthDependentViews(user){
  renderAuth(user);renderAdmin(user);
  if(user){
    await syncProfile();
    await Promise.allSettled([
      renderLeaderboard(),
      renderPublicPacks(),
      window.renderStudentPersonalPacks?.(),
      window.renderProgressDashboard?.()
    ]);
  }else{
    renderLeaderboard();
    renderPublicPacks();
    window.renderStudentPersonalPacks?.();
    window.renderProgressDashboard?.();
  }
}
window.addEventListener('8b1-auth-change',e=>{void refreshAuthDependentViews(e.detail)});renderAuth(null);renderAdmin(null);$('#closeLoginModal').onclick=()=>$('#loginModal').classList.remove('show');$('#loginModal').onclick=e=>{if(e.target===$('#loginModal'))$('#loginModal').classList.remove('show')};function authError(err){if(err.code==='auth/unauthorized-domain')return `Firebase chưa cho phép domain “${location.hostname}”. Vào Authentication → Settings → Authorized domains để thêm domain này.`;const messages={'auth/operation-not-allowed':'Hãy bật Email/Password trong Firebase Authentication trước.','auth/email-already-in-use':'Email này đã có tài khoản. Hãy đăng nhập.','auth/invalid-credential':'Email hoặc mật khẩu không đúng.','auth/weak-password':'Mật khẩu cần ít nhất 6 ký tự.'};return messages[err.code]||'Không thể thực hiện: '+err.message}async function providerLogin(provider){try{const user=await window.studyStore.signIn(provider);$('#loginModal').classList.remove('show');renderAuth(user);toast(`Chào mừng ${user.displayName||'bạn'}! Dữ liệu đang được đồng bộ.`)}catch(err){toast(authError(err))}}async function emailLogin(create){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return;try{const user=await window.studyStore.signInEmail(email,password,create);$('#loginModal').classList.remove('show');renderAuth(user);toast(create?'Đã tạo tài khoản thành công!':'Đăng nhập thành công!')}catch(err){toast(authError(err))}}$('#emailLoginForm').onsubmit=e=>{e.preventDefault();emailLogin(false)};$('#emailRegister').onclick=()=>emailLogin(true);$('#googleLogin').onclick=()=>providerLogin('google');$('#appleLogin').onclick=()=>providerLogin('apple');$('#logoutBtn').onclick=async()=>{await window.studyStore.signOut();toast('Đã đăng xuất.')};$('#openProgress').onclick=()=>{showPage('progress');$('#accountPanel').hidden=true};document.addEventListener('click',e=>{if(!$('.top-actions').contains(e.target))$('#accountPanel').hidden=true});
renderCard();renderQuiz();updateCoins();

window.addEventListener('katlearn-personal-pack-open',e=>{const words=Array.isArray(e.detail?.words)?e.detail.words:[];vocab=words;known=0;cardIndex=0;localStorage.setItem('katlearn-vocab',JSON.stringify(vocab));renderCard();renderQuiz();});
