(function(){
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const MODES={plan:["Lộ trình ôn thi","Lập kế hoạch theo ngày và mục tiêu."],lesson:["Bài học hướng dẫn","Giải thích từng bước, có ví dụ."],flashcards:["Thẻ ghi nhớ","Lật thẻ để chủ động nhớ lại."],quiz:["Trắc nghiệm","Kiểm tra và xem giải thích."],truefalse:["Đúng / Sai","Kiểm tra các nhận định quan trọng."],review:["Ôn lặp lại","Ôn đúng lúc, nhớ lâu hơn."],podcast:["Podcast học tập","Nghe nội dung bằng giọng đọc."],gaps:["Lỗ hổng kiến thức","Tìm phần chưa vững và cách khắc phục."],"mock-written":["Thi thử viết","Làm đề rồi gửi Kat AI nhận xét."],"mock-oral":["Vấn đáp mô phỏng","Luyện trả lời như với giám khảo."],tutor:["Gia sư AI","Hỏi bài, gửi ghi chú hoặc ảnh."]};
let mode="plan",result=null,resultMode="",itemIndex=0,revealed=false,selectedAnswer=-1,score=0,imageAttachment=null,busy=false,recognition=null;
const modeButtons=$$(".study-mode");
function setStatus(message,type=""){const el=$("#studyStatus");if(!el)return;el.className="study-inline-status"+(type?" study-status-"+type:"");el.textContent=String(message||"")}
function setMode(next){if(!MODES[next])return;mode=next;modeButtons.forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.mode===mode)));$("#studyGenerateLabel").textContent=mode==="tutor"?"Hỏi Kat AI":mode==="plan"?"Tạo lộ trình ôn thi":mode==="mock-written"?"Tạo đề thi thử":mode==="mock-oral"?"Bắt đầu vấn đáp":"Tạo nội dung học";$("#studyModeDescription").textContent=MODES[mode][1];$("#studyGoal").placeholder=mode==="tutor"?"Ví dụ: Vì sao phân số âm nhân với phân số âm lại ra số dương?":mode==="plan"?"Ví dụ: Ôn tập các thì tiếng Anh để kiểm tra giữa kỳ":"Ví dụ: Thì hiện tại hoàn thành, phản ứng hóa học, hệ sinh thái…";setStatus("Đang chọn: "+MODES[mode][0]+". Thêm chủ đề hoặc tài liệu rồi bắt đầu nhé.")}
modeButtons.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));
function savedPlanKey(){return "katlearn-study-studio-plan:"+String(window.studyStore?.user?.uid||"guest")}
function renderSavedPlan(){const target=$("#studySavedPlan");if(!target)return;let saved=null;try{saved=JSON.parse(localStorage.getItem(savedPlanKey())||"null")}catch(_){}if(!saved?.result?.sections?.length){target.innerHTML='<div class="study-calendar-empty">Khi tạo lộ trình ôn thi, các mốc học chính sẽ xuất hiện ở đây để bạn dễ xem lại trên thiết bị này.</div>';return}const sections=saved.result.sections.slice(0,5);target.innerHTML='<div class="study-saved-list">'+sections.map((s,i)=>'<div class="study-saved-row"><span>'+String(i+1).padStart(2,"0")+'</span><div><b>'+esc(s.heading||"Mục tiêu học tập")+'</b><small>'+esc((s.body||"").slice(0,240))+'</small></div></div>').join("")+'</div><p style="margin-top:10px">Lưu trên thiết bị · '+esc(new Date(saved.savedAt||Date.now()).toLocaleDateString("vi-VN"))+'</p><button class="study-soft-btn" type="button" id="studyRemovePlan">Xoá lộ trình đã lưu</button>';$("#studyRemovePlan")?.addEventListener("click",()=>{localStorage.removeItem(savedPlanKey());renderSavedPlan()})}
function safeSpeak(text){if(!("speechSynthesis" in window)){setStatus("Trình duyệt này chưa hỗ trợ đọc thành tiếng.");return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||"").slice(0,12000));u.lang="vi-VN";u.rate=.94;u.pitch=1;window.speechSynthesis.speak(u);setStatus("Đang đọc nội dung. Dùng nút Dừng đọc để kết thúc.")}
function speakCurrentPodcast(){if(!result)return;safeSpeak([result.title,result.summary,...(result.sections||[]).map(s=>(s.heading||"")+". "+(s.body||"")),...(result.nextSteps||[])].join("\n\n"))}
function renderSections(sections){return(sections||[]).map(s=>'<article class="study-content-block"><h3>'+esc(s.heading||"Nội dung")+'</h3><p>'+esc(s.body||"")+'</p></article>').join("")}
function renderNextSteps(steps){return steps?.length?'<div class="study-nextsteps"><h3>Bước tiếp theo</h3><ul>'+steps.map(s=>"<li>"+esc(s)+"</li>").join("")+"</ul></div>":""}
function showOutput(){$("#studyResultsEmpty").hidden=true;$("#studyOutput").hidden=false}
function renderGenericItems(items){if(!items?.length)return "";return '<div class="study-content-block"><h3>Phần tự kiểm tra</h3>'+items.map((it,i)=>'<div class="study-saved-row" style="margin-top:8px"><span>'+String(i+1).padStart(2,"0")+'</span><div><b>'+esc(it.front)+'</b><small>'+esc(it.back)+(it.explanation?" · "+esc(it.explanation):"")+'</small></div></div>').join("")+'</div>'}
function renderFlashcard(){const mount=$("#studyInteractive"),items=result?.items||[];if(!mount)return;if(!items.length){mount.innerHTML='<p class="study-mic-hint">Chưa có thẻ phù hợp. Hãy tạo lại với tài liệu cụ thể hơn.</p>';return}itemIndex=Math.max(0,Math.min(itemIndex,items.length-1));const item=items[itemIndex];mount.innerHTML='<div class="study-progress-row"><div class="study-progress-track"><span style="width:'+(((itemIndex+1)/items.length)*100)+'%"></span></div><span class="study-progress-text">Thẻ '+(itemIndex+1)+' / '+items.length+'</span></div><button class="study-flashcard '+(revealed?"revealed":"")+'" id="studyFlashcard" type="button" aria-label="Lật thẻ để xem đáp án"><small>'+(revealed?"ĐÁP ÁN":"CÂU HỎI")+'</small><h3>'+esc(revealed?item.back:item.front)+'</h3><p>'+(revealed?esc(item.explanation||"Hãy thử nói lại ý chính bằng lời của bạn."):"Nhấn để lật thẻ và tự kiểm tra trí nhớ.")+'</p></button><div class="study-card-actions"><button class="study-soft-btn" type="button" id="studyCardPrev" '+(itemIndex===0?"disabled":"")+'>← Thẻ trước</button><button class="study-soft-btn" type="button" id="studyCardFlip">'+(revealed?"Xem lại câu hỏi":"Lật thẻ")+'</button><button class="study-soft-btn" type="button" id="studyCardNext">'+(itemIndex===items.length-1?"Hoàn tất":"Thẻ tiếp →")+'</button></div>';const flip=()=>{revealed=!revealed;renderFlashcard()};$("#studyFlashcard").onclick=flip;$("#studyCardFlip").onclick=flip;$("#studyCardPrev").onclick=()=>{if(itemIndex>0){itemIndex--;revealed=false;renderFlashcard()}};$("#studyCardNext").onclick=()=>{if(itemIndex<items.length-1){itemIndex++;revealed=false;renderFlashcard()}else setStatus("Bạn đã đi hết bộ thẻ. Hãy tự diễn đạt lại những ý vừa ôn nhé.","success")}}
function renderQuiz(){const mount=$("#studyInteractive"),items=result?.items||[];if(!items.length){mount.innerHTML='<p class="study-mic-hint">Chưa có câu hỏi để hiển thị.</p>';return}itemIndex=Math.max(0,Math.min(itemIndex,items.length-1));const item=items[itemIndex],opts=(item.options||[]).length?item.options:(resultMode==="truefalse"?["Đúng","Sai"]:[]);mount.innerHTML='<div class="study-progress-row"><div class="study-progress-track"><span style="width:'+(((itemIndex+1)/items.length)*100)+'%"></span></div><span class="study-progress-text">Câu '+(itemIndex+1)+' / '+items.length+'</span></div><div class="study-content-block"><h3>Câu hỏi '+(itemIndex+1)+'</h3><p>'+esc(item.front)+'</p></div><div class="study-option-list">'+opts.map((opt,i)=>'<button type="button" class="study-option '+(selectedAnswer!==-1&&i===Number(item.answerIndex)?"correct":selectedAnswer===i?"wrong":"")+'" data-option="'+i+'" '+(selectedAnswer!==-1?"disabled":"")+'><strong>'+String.fromCharCode(65+i)+'</strong><span>'+esc(opt)+'</span></button>').join("")+'</div><div id="studyQuizFeedback" class="study-feedback" '+(selectedAnswer===-1?'hidden':'')+'>'+(selectedAnswer===-1?"":(selectedAnswer===Number(item.answerIndex)?"Chính xác! ":"Chưa đúng. ")+esc(item.explanation||item.back))+'</div><div class="study-card-actions"><span class="study-progress-text">Điểm: '+score+' / '+(selectedAnswer===-1?itemIndex:itemIndex+1)+'</span><button type="button" class="study-soft-btn" id="studyQuizNext" '+(selectedAnswer===-1?"disabled":"")+'>'+(itemIndex===items.length-1?"Xem kết quả":"Câu tiếp theo →")+'</button></div>';$$('#studyInteractive [data-option]').forEach(btn=>btn.addEventListener("click",()=>{if(selectedAnswer!==-1)return;selectedAnswer=Number(btn.dataset.option);if(selectedAnswer===Number(item.answerIndex))score++;renderQuiz()}));$("#studyQuizNext").onclick=()=>{if(itemIndex<items.length-1){itemIndex++;selectedAnswer=-1;renderQuiz()}else{mount.innerHTML='<div class="study-nextsteps"><h3>Hoàn thành · '+Math.round(score/items.length*100)+'%</h3><p>Bạn đúng '+score+'/'+items.length+' câu. Hãy xem lại câu còn nhầm rồi thử lại.</p><button class="study-soft-btn" id="studyQuizRetry" type="button">Làm lại bài này</button></div>';$("#studyQuizRetry").onclick=()=>{itemIndex=0;selectedAnswer=-1;score=0;renderQuiz()}}}}
function renderWrittenResponse(){const items=result?.items||[];return '<div class="study-content-block"><h3>Đề bài</h3>'+items.map((it,i)=>'<p style="margin-top:10px"><b>'+(items.length>1?(i+1)+". ":"")+'</b>'+esc(it.front)+'</p>').join("")+'</div><div class="study-response-form"><label for="studyWrittenAnswer">Bài làm của bạn</label><textarea id="studyWrittenAnswer" placeholder="Viết câu trả lời của bạn ở đây…"></textarea><button class="study-primary" type="button" id="studyGradeWritten">Gửi bài cho Kat AI nhận xét</button></div>'}
function renderOralResponse(){const items=result?.items||[];if(!items.length)return "";itemIndex=Math.max(0,Math.min(itemIndex,items.length-1));const item=items[itemIndex];return '<div class="study-progress-row"><div class="study-progress-track"><span style="width:'+(((itemIndex+1)/items.length)*100)+'%"></span></div><span class="study-progress-text">Câu '+(itemIndex+1)+' / '+items.length+'</span></div><div class="study-content-block"><h3>Giám khảo hỏi</h3><p>'+esc(item.front)+'</p><div class="study-card-actions"><button class="study-soft-btn" type="button" id="studySpeakQuestion">Đọc câu hỏi</button><button class="study-soft-btn" type="button" id="studyOralNext" '+(itemIndex===items.length-1?"disabled":"")+' >Câu kế tiếp →</button></div></div><div class="study-response-form"><label for="studyOralAnswer">Câu trả lời của bạn</label><textarea id="studyOralAnswer" placeholder="Gõ câu trả lời hoặc bấm thu âm nếu trình duyệt hỗ trợ…"></textarea><button class="study-soft-btn" type="button" id="studySpeechInput">● Trả lời bằng giọng nói</button><button class="study-primary" type="button" id="studyGradeOral">Gửi câu trả lời để nhận phản hồi</button><p class="study-mic-hint">Nhận diện giọng nói phụ thuộc trình duyệt và quyền micro; bạn vẫn có thể nhập câu trả lời.</p></div>'}
function renderOralResponseIntoMount(){$("#studyInteractive").innerHTML=renderOralResponse();bindOral()}
function startSpeechInput(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){setStatus("Trình duyệt chưa hỗ trợ nhận diện giọng nói. Bạn nhập câu trả lời ở trên nhé.");return}try{if(recognition)recognition.abort();recognition=new SpeechRecognition();recognition.lang=/english|ielts/i.test($("#studySubject").value)?"en-US":"vi-VN";recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>setStatus("Đang nghe câu trả lời của bạn…");recognition.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||"",box=$("#studyOralAnswer");if(box)box.value=(box.value?box.value+" ":"")+text;setStatus("Đã nhận giọng nói. Bạn có thể chỉnh lại trước khi gửi.","success")};recognition.onerror=()=>setStatus("Không nhận được giọng nói. Hãy kiểm tra quyền micro hoặc nhập câu trả lời.");recognition.onend=()=>{recognition=null};recognition.start()}catch(_){setStatus("Không thể khởi động micro. Hãy nhập câu trả lời bằng bàn phím.")}}
function bindOral(){const item=result?.items?.[itemIndex];$("#studySpeakQuestion")?.addEventListener("click",()=>safeSpeak(item?.front||""));$("#studyOralNext")?.addEventListener("click",()=>{if(itemIndex<(result?.items?.length||0)-1){itemIndex++;renderOralResponseIntoMount()}});$("#studySpeechInput")?.addEventListener("click",startSpeechInput);$("#studyGradeOral")?.addEventListener("click",()=>submitAnswer("grade-oral",$("#studyOralAnswer")?.value||"",item?.front||""))}
function renderTutorFollowup(){return '<div class="study-response-form"><label for="studyFollowup">Hỏi tiếp Kat AI</label><textarea id="studyFollowup" placeholder="Phần nào bạn muốn Kat giải thích lại theo cách khác?"></textarea><button class="study-primary" type="button" id="studyAskFollowup">Gửi câu hỏi tiếp theo</button></div>'}
function renderResult(data,which){
 result=data;resultMode=which;itemIndex=0;revealed=false;selectedAnswer=-1;score=0;showOutput();const label=MODES[which]?.[0]||({"grade-written":"Nhận xét bài viết","grade-oral":"Nhận xét vấn đáp"}[which]||"Phiên học");$("#studyOutputHeader").innerHTML='<div class="study-output-kicker">KAT AI · '+esc(label)+'</div><h2>'+esc(data.title)+'</h2><p>'+esc(data.summary)+'</p>';
 let html=renderSections(data.sections);
 if(["flashcards","review"].includes(which))html+='<div class="study-content-block"><h3>Thực hành ghi nhớ</h3><div id="studyInteractive"></div></div>';
 else if(["quiz","truefalse"].includes(which))html+='<div class="study-content-block"><h3>Bài kiểm tra tương tác</h3><div id="studyInteractive"></div></div>';
 else if(which==="mock-written")html+='<div id="studyInteractive">'+renderWrittenResponse()+'</div>';
 else if(which==="mock-oral")html+='<div id="studyInteractive">'+renderOralResponse()+'</div>';
 else if(which==="podcast")html+='<div class="study-result-tools"><button class="study-soft-btn" type="button" id="studyListen">Nghe nội dung</button><button class="study-soft-btn" type="button" id="studyStopAudio">Dừng đọc</button></div>';
 else if(which==="tutor")html+='<div class="study-result-tools"><button class="study-soft-btn" type="button" id="studyTutorListen">Đọc lời giải</button></div>'+renderTutorFollowup();
 else html+=renderGenericItems(data.items);
 html+=renderNextSteps(data.nextSteps);$("#studyOutputBody").innerHTML=html;
 if(["flashcards","review"].includes(which))renderFlashcard();if(["quiz","truefalse"].includes(which))renderQuiz();if(which==="mock-oral")bindOral();
 if(which==="mock-written")$("#studyGradeWritten")?.addEventListener("click",()=>submitAnswer("grade-written",$("#studyWrittenAnswer")?.value||"",(data.items||[]).map(x=>x.front).join("\n")));
 if(which==="tutor"){$("#studyAskFollowup")?.addEventListener("click",()=>{const q=$("#studyFollowup")?.value.trim();if(q)runAI("tutor",null,q)});$("#studyTutorListen")?.addEventListener("click",()=>safeSpeak([data.title,data.summary,...(data.sections||[]).map(s=>s.body)].join("\n")))}
 if(which==="podcast"){$("#studyListen")?.addEventListener("click",speakCurrentPodcast);$("#studyStopAudio")?.addEventListener("click",()=>{if(window.speechSynthesis)window.speechSynthesis.cancel();setStatus("Đã dừng đọc.")})}
 if(which==="plan"){try{localStorage.setItem(savedPlanKey(),JSON.stringify({savedAt:new Date().toISOString(),targetDate:$("#studyExamDate").value,result:{title:data.title,summary:data.summary,sections:data.sections,nextSteps:data.nextSteps}}));renderSavedPlan()}catch(_){setStatus("Đã tạo lộ trình nhưng trình duyệt không cho lưu bản xem lại.","error")}}
 $("#studyResultTools").innerHTML='<button class="study-soft-btn" type="button" id="studyCopyResult">Sao chép nội dung</button><button class="study-soft-btn" type="button" id="studyNewResult">Tạo phiên mới</button>';
 $("#studyCopyResult").onclick=async()=>{const text=[data.title,data.summary,...(data.sections||[]).map(s=>s.heading+"\n"+s.body),...(data.items||[]).map(i=>i.front+"\n"+i.back),...(data.nextSteps||[])].join("\n\n");try{await navigator.clipboard.writeText(text);setStatus("Đã sao chép nội dung phiên học.","success")}catch(_){setStatus("Trình duyệt không cho sao chép tự động. Bạn có thể chọn nội dung rồi sao chép.")}};
 $("#studyNewResult").onclick=()=>{$("#studyOutput").hidden=true;$("#studyResultsEmpty").hidden=false;setStatus("Chọn một chế độ và tạo phiên học tiếp theo.")};
}
function buildPayload(which,answer,focusOverride){return{mode:which,subject:$("#studySubject").value,level:$("#studyLevel").value,focus:focusOverride===undefined?$("#studyGoal").value:focusOverride,goal:$("#studyTarget").value,targetDate:$("#studyExamDate").value,minutes:$("#studyMinutes").value,material:$("#studyMaterial").value,image:imageAttachment,answer:answer||""}}
async function runAI(which=mode,answer=null,focusOverride=undefined){if(busy)return;if(!$("#studyGoal").value.trim()&&!$("#studyMaterial").value.trim()&&!imageAttachment){setStatus("Hãy nhập chủ đề/câu hỏi hoặc thêm tài liệu học trước nhé.","error");$("#studyGoal").focus();return}busy=true;const btn=$("#studyGenerate");btn.disabled=true;btn.innerHTML='<span>◌</span> Kat AI đang chuẩn bị…';setStatus("Đang đọc yêu cầu và xây dựng nội dung học.");try{const token=await window.studyStore?.getIdToken?.();if(!token){setStatus("Bạn cần đăng nhập để dùng Kat AI. Mở trang đăng nhập rồi quay lại Phòng học AI nhé.","error");return}const response=await fetch("/api/study-coach",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},cache:"no-store",body:JSON.stringify(buildPayload(which,answer,focusOverride))});let payload={};try{payload=await response.json()}catch(_){}if(!response.ok||!payload.ok)throw new Error(payload.error||"Kat AI chưa thể tạo nội dung. Hãy thử lại nhé.");renderResult(payload.result,which);setStatus("Đã tạo xong nội dung học. Hãy làm từng bước và tự kiểm tra trước khi xem đáp án.","success")}catch(error){setStatus(error?.message||"Có lỗi khi kết nối Kat AI. Hãy thử lại nhé.","error")}finally{busy=false;btn.disabled=false;btn.innerHTML='<span>✦</span><span id="studyGenerateLabel">'+(mode==="tutor"?"Hỏi Kat AI":mode==="plan"?"Tạo lộ trình ôn thi":mode==="mock-written"?"Tạo đề thi thử":mode==="mock-oral"?"Bắt đầu vấn đáp":"Tạo nội dung học")+'</span>'}}
function submitAnswer(which,answer,focus){if(!String(answer||"").trim()){setStatus("Bạn nhập câu trả lời rồi Kat mới chấm được nhé.","error");return}runAI(which,answer,focus)}
$("#studyForm")?.addEventListener("submit",e=>{e.preventDefault();runAI()});
$("#studyGoal")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey&&e.target.tagName==="INPUT"){e.preventDefault();runAI()}});
async function loadScript(src){await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error("Không tải được trình đọc PDF."));document.head.appendChild(s)})}
async function readPdf(file){if(!window.pdfjsLib)await loadScript("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js");const pdfjs=window.pdfjsLib;if(!pdfjs)throw new Error("Chưa tải được công cụ đọc PDF. Bạn có thể mở PDF và dán nội dung vào ô ghi chú.");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,parts=[];for(let i=1;i<=Math.min(pdf.numPages,12);i++){const page=await pdf.getPage(i),content=await page.getTextContent(),line=content.items.map(x=>x.str||"").join(" ");if(line.trim())parts.push("TRANG "+i+"\n"+line);if(parts.join("\n").length>=12000)break}if(!parts.length)throw new Error("PDF chưa có lớp văn bản để trích xuất. Hãy chụp ảnh trang cần học hoặc dán văn bản.");return parts.join("\n\n").slice(0,12000)}
$("#studyMaterialFile")?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;$("#studyFileName").textContent=file.name;setStatus("Đang đọc tài liệu…");try{const text=file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")?await readPdf(file):await file.text();$("#studyMaterial").value=($("#studyMaterial").value.trim()?$("#studyMaterial").value.trim()+"\n\n":"")+text.slice(0,Math.max(0,12000-$("#studyMaterial").value.length));setStatus("Đã nhập nội dung từ "+file.name+". Hãy kiểm tra văn bản trước khi gửi cho Kat AI.","success")}catch(error){setStatus(error?.message||"Không đọc được tệp. Hãy thử tệp khác hoặc dán văn bản.","error")}});
function readDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=reject;r.readAsDataURL(blob)})}
async function compressImage(file){let bitmap;try{bitmap=await createImageBitmap(file)}catch(_){throw new Error("Không thể mở ảnh này. Hãy chọn ảnh JPG, PNG hoặc WebP.")}const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();let blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.76));if(!blob)throw new Error("Không thể xử lý ảnh.");if(blob.size>900000)blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.55));const dataUrl=await readDataUrl(blob),data=dataUrl.split(",")[1]||"";if(data.length>1400000)throw new Error("Ảnh còn quá lớn. Hãy cắt ảnh lấy đúng phần bài cần hỏi.");return{mimeType:"image/jpeg",data}}
$("#studyImageFile")?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;setStatus("Đang tối ưu ảnh để Kat AI đọc dễ hơn…");try{imageAttachment=await compressImage(file);$("#studyImagePreview").hidden=false;$("#studyImageThumb").src="data:image/jpeg;base64,"+imageAttachment.data;$("#studyImageLabel").textContent=file.name;setStatus("Đã thêm ảnh. Ảnh chỉ được gửi tới Kat AI khi bạn bấm tạo nội dung.","success")}catch(error){imageAttachment=null;setStatus(error?.message||"Không xử lý được ảnh.","error")}});
$("#studyRemoveImage")?.addEventListener("click",()=>{imageAttachment=null;$("#studyImageFile").value="";$("#studyImagePreview").hidden=true;$("#studyImageThumb").removeAttribute("src");$("#studyImageLabel").textContent=""});
$("#studyClearMaterial")?.addEventListener("click",()=>{$("#studyMaterial").value="";$("#studyMaterialFile").value="";$("#studyFileName").textContent="Chưa có tệp"});
window.addEventListener("8b1-auth-change",renderSavedPlan);window.addEventListener("katlearn-account-ready",renderSavedPlan);renderSavedPlan();setMode("plan");
})();