(function(){
const data=[['night','Night Study',120,'assets/1/bg-cat-night.svg'],['sky','Sky Day',150,'assets/1/bg-sky.svg'],['pink','Pink Mood',180,'assets/1/bg-pink.svg'],['ocean','Ocean Calm',220,'assets/1/bg-ocean.svg'],['lavender','Lavender Dream',260,'assets/1/bg-lavender.svg']];
const $=s=>document.querySelector(s),num=n=>Number(n||0).toLocaleString('en-US');
function setBg(id,save){const x=data.find(a=>a[0]===id);if(!x){document.body.style.removeProperty('background-image');if(save)localStorage.removeItem('katlearn-theme');return}document.body.style.backgroundImage=`url('${x[3]}')`;document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';document.body.style.backgroundPosition='center';if(save)localStorage.setItem('katlearn-theme',id)}
function owned(){return new Set(JSON.parse(localStorage.getItem('katlearn-owned-themes')||'[]'))}
function draw(){const g=$('.shop-grid');if(!g)return;const have=owned(),cur=localStorage.getItem('katlearn-theme')||'default';g.innerHTML=data.map(x=>`<article class="shop-theme-card"><div class="shop-theme-preview" style="background-image:url('${x[3]}')"></div><h3>${x[1]}</h3><p>Hình nền KatLearn</p><b>🪙 ${num(x[2])}</b><button class="shop-buy-theme" data-price="${x[2]}" data-theme-id="${x[0]}" data-item-id="theme-${x[0]}">${have.has('theme-'+x[0])?'✓ Đã mua':'Mua'}</button><button class="shop-apply-theme" data-theme-id="${x[0]}" ${have.has('theme-'+x[0])||cur===x[0]?'':'disabled'}>${cur===x[0]?'✓ Đang áp dụng':'Áp dụng'}</button></article>`).join('')}
async function restore(){if(!window.studyStore?.user)return;try{const p=await window.studyStore.loadProfile();if(p){localStorage.setItem('katlearn-vocab',JSON.stringify(Array.isArray(p.vocab)?p.vocab:[]));localStorage.setItem('katlearn-owned-themes',JSON.stringify(Array.isArray(p.ownedThemes)?p.ownedThemes:[]));if(p.themeId)localStorage.setItem('katlearn-theme',p.themeId);setBg(p.themeId||'default',false)}}catch(e){}}
document.addEventListener('click',e=>{const a=e.target.closest?.('.shop-apply-theme');if(a){e.preventDefault();e.stopImmediatePropagation();const id=a.dataset.themeId;setBg(id,true);if(window.studyStore?.user)window.studyStore.saveProfile({themeId:id});setTimeout(draw,100)}const b=e.target.closest?.('.shop-buy-theme');if(b){setTimeout(async()=>{const s=owned();s.add(b.dataset.itemId);localStorage.setItem('katlearn-owned-themes',JSON.stringify([...s]));if(window.studyStore?.user)await window.studyStore.saveProfile({ownedThemes:[...s]});draw()},1200)}},true);
window.addEventListener('8b1-auth-change',async()=>{await restore();draw()});document.addEventListener('DOMContentLoaded',async()=>{await restore();draw();setBg(localStorage.getItem('katlearn-theme')||'default',false)},{once:true});
})();
