(function(){
const data=[['night','Night Study',120,'assets/1/bg-cat-night.svg'],['sky','Sky Day',150,'assets/1/bg-sky.svg'],['pink','Pink Mood',180,'assets/1/bg-pink.svg'],['ocean','Ocean Calm',220,'assets/1/bg-ocean.svg'],['lavender','Lavender Dream',260,'assets/1/bg-lavender.svg']];
const $=s=>document.querySelector(s),num=n=>Number(n||0).toLocaleString('en-US');
const style=document.createElement('style');style.textContent='.shop-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.shop-theme-card{background:#fff;border:1px solid #ececf3;border-radius:22px;padding:12px;box-shadow:0 10px 30px #4c426312}.shop-theme-preview{height:150px;border-radius:16px;background-size:cover;background-position:center;margin-bottom:12px}.shop-theme-card h3{margin:4px 0;font:700 18px Fredoka,sans-serif}.shop-theme-card p{margin:0 0 10px;color:#8792a5;font-size:11px}.shop-theme-card>b{display:block;margin-bottom:10px}.shop-theme-card button{border:0;border-radius:10px;padding:9px 12px;margin-right:6px;cursor:pointer;font:700 11px "Be Vietnam Pro",sans-serif;background:#f47c93;color:#fff}.shop-theme-card .shop-apply-theme{background:#5d4fea}.shop-theme-card button:disabled{opacity:.45;cursor:not-allowed}';document.head.appendChild(style);
function setBg(id,save){const x=data.find(a=>a[0]===id);if(!x){document.body.style.removeProperty('background-image');if(save)localStorage.removeItem('katlearn-theme');return}document.body.style.backgroundImage=`url('${x[3]}')`;document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';document.body.style.backgroundPosition='center';if(save)localStorage.setItem('katlearn-theme',id)}
function owned(){return new Set(JSON.parse(localStorage.getItem('katlearn-owned-themes')||'[]'))}
function draw(){const g=$('.shop-grid');if(!g)return;const have=owned(),cur=localStorage.getItem('katlearn-theme')||'default';g.innerHTML=data.map(x=>`<article class="shop-theme-card"><div class="shop-theme-preview" style="background-image:url('${x[3]}')"></div><h3>${x[1]}</h3><p>Hình nền KatLearn</p><b>🪙 ${num(x[2])}</b><button class="shop-buy-theme" data-price="${x[2]}" data-theme-id="${x[0]}" data-item-id="theme-${x[0]}">${have.has('theme-'+x[0])?'✓ Đã mua':'Mua'}</button><button class="shop-apply-theme" data-theme-id="${x[0]}" ${have.has('theme-'+x[0])||cur===x[0]?'':'disabled'}>${cur===x[0]?'✓ Đang áp dụng':'Áp dụng'}</button></article>`).join('')}
async function restore(){if(!window.studyStore?.user)return false;try{const p=await window.studyStore.loadProfile();if(p){const vv=Array.isArray(p.vocab)?p.vocab:[];localStorage.setItem('katlearn-vocab',JSON.stringify(vv));localStorage.setItem('katlearn-owned-themes',JSON.stringify(Array.isArray(p.ownedThemes)?p.ownedThemes:[]));localStorage.setItem('katlearn-stats',JSON.stringify({questionsAnswered:Number(p.questionsAnswered||0),correctAnswers:Number(p.correctAnswers||0)}));if(p.themeId)localStorage.setItem('katlearn-theme',p.themeId);else localStorage.removeItem('katlearn-theme');if(typeof vocab!=='undefined')vocab=vv;if(typeof known!=='undefined')known=Number(p.knownWords||0);if(typeof coins!=='undefined')coins=Number(p.coins||0);if(typeof energy!=='undefined')energy=Number(p.energy||0);if(typeof updateCoins==='function')updateCoins();if(typeof renderCard==='function')renderCard();if(typeof renderQuiz==='function')renderQuiz();if(typeof renderVocabularyViews==='function')renderVocabularyViews();if(typeof renderWordList==='function')renderWordList();const k=$('#knownCount');if(k)k.textContent=Number(p.knownWords||0);const t=$('#totalWords');if(t)t.textContent=vv.length;const cards=document.querySelectorAll('#progress .stat-grid>div'),a=Number(p.questionsAnswered||0),c=Number(p.correctAnswers||0),acc=a?Math.round(c/a*100):0,vals=[Number(p.knownWords||0),acc+'%',Number(p.streak||0),num(p.coins)];cards.forEach((x,i)=>{const h=x.querySelector('h2');if(h)h.textContent=vals[i]});setBg(p.themeId||'default',false)}else{localStorage.setItem('katlearn-vocab','[]');localStorage.setItem('katlearn-owned-themes','[]');localStorage.setItem('katlearn-stats','{"questionsAnswered":0,"correctAnswers":0}');localStorage.removeItem('katlearn-theme')}return true}catch(e){console.warn('[KatLearn restore]',e);return false}}
document.addEventListener('click',e=>{const a=e.target.closest?.('.shop-apply-theme');if(a){e.preventDefault();e.stopImmediatePropagation();const id=a.dataset.themeId;setBg(id,true);if(window.studyStore?.user)window.studyStore.saveProfile({themeId:id});setTimeout(draw,100);return}const b=e.target.closest?.('.shop-buy-theme');if(b){setTimeout(async()=>{const s=owned();s.add(b.dataset.itemId);localStorage.setItem('katlearn-owned-themes',JSON.stringify([...s]));if(window.studyStore?.user)await window.studyStore.saveProfile({ownedThemes:[...s]});draw()},1200)}},true);
async function boot(){if(!window.studyStore?.user)return;const uid=window.studyStore.userId,key='katlearn-restored-'+uid;const ok=await restore();if(ok&&!sessionStorage.getItem(key)){sessionStorage.setItem(key,'1');location.reload();return}draw()}
window.addEventListener('8b1-auth-change',boot);document.addEventListener('DOMContentLoaded',async()=>{await boot();draw();setBg(localStorage.getItem('katlearn-theme')||'default',false)},{once:true});
})();
